"""Add soft deleted field to base model

Revision ID: 245c70abd0a7
Revises: 8f2bb509e907
Create Date: 2025-04-29 20:43:36.821293

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '245c70abd0a7'
down_revision = '8f2bb509e907'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('soft_deleted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('soft_deleted', sa.Boolean(), nullable=False, server_default=sa.text('FALSE'), ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'soft_deleted')
    op.drop_column('budget', 'soft_deleted')
    # ### end Alembic commands ###
