"""Add owner field to budget model

Revision ID: 52d7b790a59d
Revises: 2fb4d7de6de3
Create Date: 2025-05-13 22:04:41.450366

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '52d7b790a59d'
down_revision = '2fb4d7de6de3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('budget', sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('budget', sa.Column('owner', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_budget_owner'), 'budget', ['owner'], unique=False)
    op.create_foreign_key(None, 'budget', 'users', ['owner'], ['id'])
    op.add_column('users', sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('users', sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_constraint(None, 'budget', type_='foreignkey')
    op.drop_index(op.f('ix_budget_owner'), table_name='budget')
    op.drop_column('budget', 'owner')
    op.drop_column('budget', 'updated_by')
    op.drop_column('budget', 'created_by')
    # ### end Alembic commands ###
