"""Add user id to budget table

Revision ID: 741acb40b996
Revises: c6efd2dec955
Create Date: 2025-05-20 15:31:19.855797

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # NEW


# revision identifiers, used by Alembic.
revision = "741acb40b996"
down_revision = "c6efd2dec955"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("budget", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(None, "budget", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "budget", type_="foreignkey")
    op.drop_column("budget", "user_id")
    # ### end Alembic commands ###
