"""Add unique constraint on name and owner

Revision ID: f00432d5f40d
Revises: 52d7b790a59d
Create Date: 2025-05-14 18:24:44.169905

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'f00432d5f40d'
down_revision = '52d7b790a59d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_owner_budget_name', 'budget', ['owner', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_owner_budget_name', 'budget', type_='unique')
    # ### end Alembic commands ###
