# Use Node.js version 14 as the base image
FROM node:14

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY frontend/expense-tracker-fe/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY frontend/expense-tracker-fe .

# Set the port to 3000
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
